In [67]:
from myptv.particle_matching_mod import matching_with_marching_particles_algorithm
from myptv.io_mod import read_from_file, write_to_file

import numpy as np
import pandas as pd

In [79]:
from myptv.imaging_mod import camera_wrapper, img_system

camNames = ['cam1','cam2','cam3']
cams = [camera_wrapper(cn,'.') for cn in camNames]
for c in cams:
    c.load()

imsys = img_system(cams)
blob_files = ['blobs_cam1.hdf5', 'blobs_cam2.hdf5', 'blobs_cam3.hdf5']

ROI= (0.0, 70.0, 0.0, 70.0, -50.0, 15.0)
voxel_size = 20
N0 = 0
max_d_err = 0.25
min_cam_match = 3

In [80]:
mp = matching_with_marching_particles_algorithm(imsys, blob_files, max_d_err, ROI, N0, 
                                                 voxel_size, min_cam_match=3, reverse_eta_zeta=True)

mp.get_blobs()

initializing matcher:

loading blob data...

In [81]:
savename = 'test_matching.hdf5'

frames = sorted(list(mp.frames))

frm_res = mp.match_frame(frames[0], savename, False)

for frm in frames[1:]:
    frm_res = mp.match_frame(frm, savename, True)

frame: 0
Found 28 matches: 0 from prev. frame + 28 new
saved 28 samples in test_matching.hdf5


frame: 1
Found 28 matches: 28 from prev. frame + 0 new
added 28 samples to test_matching.hdf5


frame: 2
Found 31 matches: 27 from prev. frame + 4 new
added 31 samples to test_matching.hdf5


frame: 3
Found 30 matches: 26 from prev. frame + 4 new
added 30 samples to test_matching.hdf5


frame: 4
Found 28 matches: 25 from prev. frame + 3 new
added 28 samples to test_matching.hdf5


frame: 5
Found 34 matches: 25 from prev. frame + 9 new
added 34 samples to test_matching.hdf5


frame: 6
Found 33 matches: 29 from prev. frame + 4 new
added 33 samples to test_matching.hdf5

In [82]:
read_from_file(savename)

             0          1          2     3     4     5         6    7
0    35.559334  38.822567 -47.864258  26.0  21.0  23.0  0.022239  0.0
1    31.282070  55.075478   4.795811   8.0   9.0   6.0  0.015915  0.0
2    31.430182  17.168634 -16.236273  48.0  35.0  44.0  0.021983  0.0
3    42.026436   1.878798   2.049644  73.0  64.0  64.0  0.012532  0.0
4    10.350501  28.903370 -15.209252  40.0  26.0  35.0  0.023948  0.0
..         ...        ...        ...   ...   ...   ...       ...  ...
207  15.402047   0.513229  11.252131  87.0  70.0  67.0  0.060355  6.0
208  12.805474  47.289734   7.626522  25.0  20.0  15.0  0.012584  6.0
209  54.784004  28.661823  -1.069655  43.0  30.0  36.0  0.036748  6.0
210  23.527504  40.501186   1.834135  31.0  22.0  22.0  0.023048  6.0
211  49.928284   7.823684 -38.024479  61.0  53.0  55.0  0.133649  6.0

[212 rows x 8 columns]

In [46]:
cands = mp.find_candidates_with_two_cameras(0, 1, 0)

In [49]:
frame = 0

mp.generate_blob_trees(frame)
print(mp.match_nearest_blobs(cands[0], frame))

None

In [60]:
x0 = np.array([6.432, 17.481, -3.761])

for cn in [0,1,2]:
    proj = mp.imsys.cameras[cn].projection(x0)
    nn = mp.B_ik_trees[cn].query(proj)
    print(proj, nn)

[328.64884404 708.1268437 ] (0.1880539236301909, np.int64(67))
[308.48256772 699.83816338] (20.232030644378387, np.int64(22))
[366.95505125 647.55347752] (62.567394002500784, np.int64(17))

In [75]:
blobs_hdf5 = read_from_file('blobs_cam2.hdf5')
blobs_hdf5

              0           1    2    3      4    5
0    131.979996  390.440002  3.0  2.0  123.0  0.0
1    177.630005  464.649994  2.0  2.0   79.0  0.0
2    182.020004  752.200012  3.0  3.0   51.0  0.0
3    203.740005  654.419983  3.0  2.0   53.0  0.0
4    208.809998  517.099976  3.0  3.0  185.0  0.0
..          ...         ...  ...  ...    ...  ...
486  908.450012  700.489990  2.0  2.0   49.0  6.0
487  912.109985  592.700012  3.0  3.0  120.0  6.0
488  914.309998  438.869995  4.0  3.0  356.0  6.0
489  918.500000  489.980011  4.0  5.0  735.0  6.0
490  919.739990  957.960022  2.0  3.0   47.0  6.0

[491 rows x 6 columns]